//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyEnvios_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Chofer
    {
        public tb_Chofer()
        {
            this.tb_Transporte = new HashSet<tb_Transporte>();
        }
    
        public string IDChofer { get; set; }
        public string Nombre { get; set; }
        public string Apellido_pat { get; set; }
        public string Apellido_mat { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public int DNI { get; set; }
        public string NumeroBrevete { get; set; }
        public string TipoBrevete { get; set; }
    
        public virtual ICollection<tb_Transporte> tb_Transporte { get; set; }
    }
}
