//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyEnvios_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Ciudad
    {
        public tb_Ciudad()
        {
            this.tb_Destino = new HashSet<tb_Destino>();
        }
    
        public string IDCiudad { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Kilometros { get; set; }
    
        public virtual ICollection<tb_Destino> tb_Destino { get; set; }
    }
}
