//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyEnvios_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_TipoCargo
    {
        public tb_TipoCargo()
        {
            this.tb_Cargo = new HashSet<tb_Cargo>();
        }
    
        public string IDTipoCargo { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<tb_Cargo> tb_Cargo { get; set; }
    }
}
