//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyEnvios_ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Transporte
    {
        public string IDTransporte { get; set; }
        public string IDChofer { get; set; }
        public string IDMarca { get; set; }
        public string Modelo { get; set; }
        public string Placa { get; set; }
        public string TarjetaProp { get; set; }
    
        public virtual tb_Chofer tb_Chofer { get; set; }
        public virtual tb_Marca tb_Marca { get; set; }
    }
}
